# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'PartiesTonight' do
pod 'Google/SignIn', :inhibit_warnings => true
pod 'Fabric'
pod 'TwitterKit'
pod 'TwitterCore'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
end
