# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'PartiesTonight' do
pod 'Google/SignIn'
pod 'Fabric'
pod 'TwitterKit'
pod 'TwitterCore'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
end
